import type { BrandProfile } from "../brand/profile";
import type { CreativeBriefing } from "./concepts";
import type { CaptionGenerationInput } from "./captions";

export function buildCreativePromptBrandContext(brandProfile: BrandProfile) {
  const { logoDataUrl, ...profileWithoutEmbeddedLogo } = brandProfile;

  return {
    ...profileWithoutEmbeddedLogo,
    logo: {
      hasLogo: Boolean(logoDataUrl || brandProfile.logoFileName),
      fileName: brandProfile.logoFileName,
      embeddedAssetOmitted: Boolean(logoDataUrl),
    },
  };
}

export function buildCreativeConceptPrompt(
  brandProfile: BrandProfile,
  briefing: CreativeBriefing,
) {
  return [
    "Crie exatamente 3 conceitos criativos distintos para um post de Instagram.",
    "",
    "Regra de escopo:",
    "- Gere apenas conceitos criativos.",
    "- Nao escreva legenda final.",
    "- Nao escreva roteiro completo de carrossel.",
    "- Nao gere arte final.",
    "- Nao mencione ferramentas de publicacao, Zernio, Recraft ou automacao.",
    "- Cada conceito deve ser executavel depois por um motor visual, mas ainda nao deve virar asset.",
    "- Responda somente com JSON valido.",
    "- Nao use markdown.",
    "- Nao coloque texto antes ou depois do JSON.",
    "",
    "Qualidade esperada:",
    "- Os 3 conceitos precisam ser realmente diferentes entre si.",
    "- Evite linguagem generica, publicitaria ou com cara de IA.",
    "- Traga uma decisao clara de formato, narrativa, visual e copy.",
    "- Use as referencias da marca como sinais, nao como copia literal.",
    "- Prefira especificidade, tensao e ponto de vista.",
    "",
    "Perfil da marca:",
    JSON.stringify(buildCreativePromptBrandContext(brandProfile), null, 2),
    "",
    "Briefing do post:",
    JSON.stringify(briefing, null, 2),
    "",
    "Contrato de saida obrigatorio:",
    JSON.stringify(
      {
        concepts: [
          {
            title: "string",
            centralIdea: "string",
            hook: "string",
            recommendedFormat: "string",
            estimatedSlides: 1,
            narrativeStructure: ["string", "string", "string"],
            visualDirection: {
              visualFamily: "string",
              composition: "string",
              typography: "string",
              colorUsage: "string",
              assetStrategy: "string",
            },
            copyDirection: {
              style: "string",
              openingMove: "string",
              voiceNotes: "string",
            },
            whyItFitsBrand: "string",
            differentiationFromOthers: "string",
            riskNotes: "string",
          },
          {
            title: "string",
            centralIdea: "string",
            hook: "string",
            recommendedFormat: "string",
            estimatedSlides: 1,
            narrativeStructure: ["string", "string", "string"],
            visualDirection: {
              visualFamily: "string",
              composition: "string",
              typography: "string",
              colorUsage: "string",
              assetStrategy: "string",
            },
            copyDirection: {
              style: "string",
              openingMove: "string",
              voiceNotes: "string",
            },
            whyItFitsBrand: "string",
            differentiationFromOthers: "string",
            riskNotes: "string",
          },
          {
            title: "string",
            centralIdea: "string",
            hook: "string",
            recommendedFormat: "string",
            estimatedSlides: 1,
            narrativeStructure: ["string", "string", "string"],
            visualDirection: {
              visualFamily: "string",
              composition: "string",
              typography: "string",
              colorUsage: "string",
              assetStrategy: "string",
            },
            copyDirection: {
              style: "string",
              openingMove: "string",
              voiceNotes: "string",
            },
            whyItFitsBrand: "string",
            differentiationFromOthers: "string",
            riskNotes: "string",
          },
        ],
        decisionTrace: {
          brandSignals: ["string", "string"],
          briefingSignals: ["string", "string"],
          differentiationStrategy: "string",
        },
      },
      null,
      2,
    ),
  ].join("\n");
}

export function buildCaptionPrompt(input: CaptionGenerationInput) {
  const visualCopy = {
    headline: input.typographicPiece.copy.headline,
    support: input.typographicPiece.copy.support,
    cta: input.typographicPiece.copy.cta,
    selectedVariantId: input.typographicPiece.selectedVariantId,
  };

  return [
    "Crie exatamente 3 opcoes de legenda para o post de Instagram abaixo.",
    "",
    "Regra de escopo:",
    "- Gere apenas legenda, primeiro comentario, hashtags e revisao estrategica.",
    "- Nao gere arte, carrossel, imagem, automacao, calendario ou publicacao.",
    "- A legenda deve complementar a peca visual. Nao repita literalmente a headline, o apoio ou o CTA visual.",
    "- Otimize para clareza de abertura, comentario real, compartilhamento e salvamento, sem prometer viralizacao.",
    "- Evite engagement bait, pedido artificial de curtida, cliche motivacional e linguagem generica de IA.",
    "- Nao use travessao longo ou estrutura excessivamente simetrica.",
    "- Nao prometa resultado garantido, crescimento garantido ou aumento numerico sem fonte.",
    "- Responda somente com JSON valido.",
    "- Nao use markdown.",
    "- Nao coloque texto antes ou depois do JSON.",
    "",
    "Como pensar a legenda:",
    "- A primeira linha precisa ter cena, tensao ou observacao concreta.",
    "- A legenda deve soar humana, com ritmo natural e sem conclusao professoral.",
    "- Use a voz da marca e respeite palavras proibidas.",
    "- O primeiro comentario deve abrir conversa real ou entregar um recurso, se o briefing justificar.",
    "- Hashtags devem ser poucas, especificas e sem poluir o post.",
    "- Cada variante deve ter uma funcao estrategica diferente.",
    "",
    "Variantes obrigatorias:",
    "- short-dry: curta, seca, memoravel, com pouco texto.",
    "- conversation: feita para comentario e resposta humana.",
    "- strategic-context: adiciona contexto, mecanismo ou tese sem virar artigo.",
    "",
    "Perfil da marca:",
    JSON.stringify(buildCreativePromptBrandContext(input.brandProfile), null, 2),
    "",
    "Briefing do post:",
    JSON.stringify(input.briefing, null, 2),
    "",
    "Conceito escolhido:",
    JSON.stringify(input.selectedConcept, null, 2),
    "",
    "Copy visual final da peca tipografica:",
    JSON.stringify(visualCopy, null, 2),
    "",
    "Contrato de saida obrigatorio:",
    JSON.stringify(
      {
        variants: [
          {
            id: "short-dry",
            label: "Curta e seca",
            strategicRole: "string",
            caption: "string",
            firstComment: "string",
            hashtags: ["string"],
            review: {
              sharePotential: "baixo|medio|alto",
              commentPotential: "baixo|medio|alto",
              savePotential: "baixo|medio|alto",
              openingClarity: "baixo|medio|alto",
              brandFit: "baixo|medio|alto",
              aiRisk: "baixo|medio|alto",
              promiseRisk: "baixo|medio|alto",
              rationale: "string",
              improvementNotes: ["string", "string"],
            },
          },
          {
            id: "conversation",
            label: "Conversa",
            strategicRole: "string",
            caption: "string",
            firstComment: "string",
            hashtags: ["string"],
            review: {
              sharePotential: "baixo|medio|alto",
              commentPotential: "baixo|medio|alto",
              savePotential: "baixo|medio|alto",
              openingClarity: "baixo|medio|alto",
              brandFit: "baixo|medio|alto",
              aiRisk: "baixo|medio|alto",
              promiseRisk: "baixo|medio|alto",
              rationale: "string",
              improvementNotes: ["string", "string"],
            },
          },
          {
            id: "strategic-context",
            label: "Contexto estrategico",
            strategicRole: "string",
            caption: "string",
            firstComment: "string",
            hashtags: ["string"],
            review: {
              sharePotential: "baixo|medio|alto",
              commentPotential: "baixo|medio|alto",
              savePotential: "baixo|medio|alto",
              openingClarity: "baixo|medio|alto",
              brandFit: "baixo|medio|alto",
              aiRisk: "baixo|medio|alto",
              promiseRisk: "baixo|medio|alto",
              rationale: "string",
              improvementNotes: ["string", "string"],
            },
          },
        ],
      },
      null,
      2,
    ),
  ].join("\n");
}
