import crypto from "node:crypto";
import { requireAdminRequest } from "@/lib/auth";

export const dynamic = "force-dynamic";

export async function GET(request: Request) {
  const authError = await requireAdminRequest(request);

  if (authError) {
    return authError;
  }

  const webhookSecret = process.env.ZERNIO_WEBHOOK_SECRET;

  if (!webhookSecret) {
    return Response.json(
      {
        ok: false,
        error: "ZERNIO_WEBHOOK_SECRET não está configurado neste deployment.",
      },
      { status: 503 },
    );
  }

  const eventId = crypto.randomUUID();
  const payload = {
    id: eventId,
    event: "webhook.test",
    message: "Self-test generated by Social Media Automator.",
    timestamp: new Date().toISOString(),
  };
  const rawBody = JSON.stringify(payload);
  const signature = crypto
    .createHmac("sha256", webhookSecret)
    .update(rawBody)
    .digest("hex");
  const webhookUrl = new URL("/api/webhooks/zernio", request.url);

  const response = await fetch(webhookUrl, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      "X-Zernio-Event-Id": eventId,
      "X-Zernio-Signature": signature,
    },
    body: rawBody,
    cache: "no-store",
  });
  const responseBody = await response.text();

  return Response.json(
    {
      ok: response.ok,
      status: response.status,
      webhookUrl: webhookUrl.toString(),
      eventId,
      responseBody,
    },
    { status: response.ok ? 200 : 502 },
  );
}
